# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # the base virtual machine ubuntu 14.04 64bit
  config.vm.box = "ubuntu/trusty64"

  # forward the 8888 port, to acccess to jupyter web interface from the host
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  # specify the memory for the virtual machine
  config.vm.provider "virtualbox" do |vb|
    # if you need more memory change this value
    vb.memory = 1024
    # if you need more cpu uncomment the next line
    #vb.cpus = 2
  end

  # install python2, python3, jupyter and libraries with all dependencies
  config.vm.provision "shell", inline: <<-SHELL
    echo "deb http://downloads.skewed.de/apt/trusty trusty universe" | sudo tee -a /etc/apt/sources.list
    echo "deb-src http://downloads.skewed.de/apt/trusty trusty universe" | sudo tee -a /etc/apt/sources.list
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install -y build-essential
    sudo apt-get install -y libxml2-dev zlib1g-dev g++-4.9
    # install python2
    sudo apt-get install -y python-dev python-setuptools python-pip
    sudo apt-get install --force-yes -y python-graph-tool
    sudp pip install numpy scipy matplotlib
    sudo pip install jinja2 six requests tornado pyyaml python-dateutil
    sudo pip install statsmodels seaborn
    sudo pip install bokeh pandas sympy
    sudo pip install ipykernel ipywidgets
    sudo pip install jgraph networkx python-igraph
    # install python3
    sudo apt-get install -y python3-dev python3-setuptools python3-pip
    sudo apt-get install --force-yes -y python3-graph-tool
    sudo pip3 install numpy scipy matplotlib
    sudo pip3 install jinja2 six requests tornado pyyaml python-dateutil
    sudo pip3 install statsmodels seaborn
    sudo pip3 install bokeh pandas sympy
    sudo pip3 install jupyter ipykernel ipywidgets
    sudo pip3 install jgraph networkx python-igraph
    # install jupyter
    sudo python2 -m ipykernel install
    sudo python3 -m ipykernel install
    #sympy?
    mkdir -p /vagrant/notebook
  SHELL

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    jupyter notebook --notebook-dir=/vagrant/notebook --no-browser --ip=0.0.0.0 &
  SHELL

end
